export const registerAppRoutes = (app, { auth, body, c, id, now, addEvent, publicApp, starterDefinition, compileDefinition, serializeDefinition, manifestOf, blockingPublishDiagnostics, publishSnapshot, rollbackSnapshot, requireApp }) => {
  app.get('/api/apps', { preHandler: auth }, async (request) => (await c('apps').find({ tenant_id: request.tenant.id }).sort({ updated_at: -1 }).toArray()).map(publicApp));
  app.post('/api/onboard', { preHandler: auth }, async (request, reply) => {
    const { name, goal, concepts } = body(request); if (!name?.trim() || !goal?.trim()) return reply.code(400).send({ error: '请填写应用名称和目标' });
    const definition = starterDefinition({ name: name.trim(), goal: goal.trim(), concepts: Array.isArray(concepts) ? concepts.filter(Boolean).slice(0, 12) : [] }); const manifest = compileDefinition(definition); const appId = id(); const timestamp = now();
    await c('apps').insertOne({ id: appId, tenant_id: request.tenant.id, name: name.trim(), description: goal.trim(), published_definition: definition, published_manifest_json: manifest, draft_definition: definition, draft_manifest_json: manifest, published_version: 1, draft_version: 1, created_at: timestamp, updated_at: timestamp });
    await c('app_versions').insertOne({ id: id(), app_id: appId, version: 1, definition, manifest_json: manifest, status: 'published', created_at: timestamp, published_at: timestamp, previous_version: null });
    await addEvent({ tenantId: request.tenant.id, appId, type: 'app.published', message: `应用「${name.trim()}」已创建并发布 v1`, actor: 'human' });
    return reply.code(201).send({ app: publicApp(await c('apps').findOne({ id: appId })) });
  });
  app.get('/api/apps/:id', { preHandler: [auth, requireApp] }, async (request) => publicApp(request.appRecord));
  app.get('/api/apps/:id/definition', { preHandler: [auth, requireApp] }, async (request) => ({ definition: request.appRecord.draft_definition ?? request.appRecord.definition, files: serializeDefinition(request.appRecord.draft_definition ?? request.appRecord.definition), manifest: manifestOf(request.appRecord, 'draft'), version: request.appRecord.draft_version }));
  app.put('/api/apps/:id/definition', { preHandler: [auth, requireApp] }, async (request, reply) => {
    const definition = body(request).definition; if (typeof definition !== 'string' || !definition.trim()) return reply.code(400).send({ error: 'definition 必须是单一 APP.md 文本内容' }); const current = request.appRecord; const nextVersion = Math.max(current.published_version, current.draft_version) + 1; const manifest = compileDefinition(definition); if (manifest.diagnostics.some((item) => item.level === 'error')) return reply.code(422).send({ error: manifest.diagnostics.map((item) => item.message).join('；'), diagnostics: manifest.diagnostics }); const timestamp = now();
    await c('apps').updateOne({ id: current.id }, { $set: { draft_definition: definition, draft_manifest_json: manifest, draft_version: nextVersion, updated_at: timestamp } }); await c('app_versions').insertOne({ id: id(), app_id: current.id, version: nextVersion, definition, manifest_json: manifest, status: 'draft', created_at: timestamp, published_at: null, previous_version: current.published_version }); await addEvent({ tenantId: current.tenant_id, appId: current.id, type: 'app.draft', message: `已生成定义 v${nextVersion} 草稿`, actor: 'builder' }); return { version: nextVersion, definition, files: serializeDefinition(definition), manifest };
  });
  app.post('/api/apps/:id/compile', { preHandler: [auth, requireApp] }, async (request) => { const manifest = compileDefinition(request.appRecord.draft_definition ?? request.appRecord.definition); return { ok: !manifest.diagnostics.some((item) => item.level === 'error'), manifest, draft_version: request.appRecord.draft_version }; });
  app.post('/api/apps/:id/publish', { preHandler: [auth, requireApp] }, async (request, reply) => { const current = request.appRecord; const manifest = manifestOf(current, 'draft'); const diagnostics = blockingPublishDiagnostics(manifest); if (diagnostics.length) return reply.code(422).send({ error: '当前应用不满足发布条件', diagnostics }); if (!current.draft_version || current.draft_version <= current.published_version) return reply.code(400).send({ error: '没有待发布草稿' }); const timestamp = now(); const update = await c('apps').updateOne({ id: current.id, draft_version: current.draft_version, published_version: current.published_version }, { $set: publishSnapshot(current, timestamp) }); if (!update.modifiedCount) return reply.code(409).send({ error: '应用版本已变化，请重新发布' }); await c('app_versions').updateMany({ app_id: current.id, status: 'published' }, { $set: { status: 'archived' } }); await c('app_versions').updateOne({ app_id: current.id, version: current.draft_version }, { $set: { status: 'published', published_at: timestamp } }); await addEvent({ tenantId: current.tenant_id, appId: current.id, type: 'app.published', message: `已发布 v${current.draft_version}`, actor: 'builder' }); return { ok: true, version: current.draft_version }; });
  app.post('/api/apps/:id/rollback', { preHandler: [auth, requireApp] }, async (request, reply) => { const target = Number(body(request).version); const version = await c('app_versions').findOne({ app_id: request.appRecord.id, version: target }); if (!version) return reply.code(404).send({ error: '版本不存在' }); const timestamp = now(); await c('app_versions').updateMany({ app_id: request.appRecord.id, status: 'published' }, { $set: { status: 'archived' } }); await c('app_versions').updateOne({ id: version.id }, { $set: { status: 'published', published_at: timestamp } }); await c('apps').updateOne({ id: request.appRecord.id }, { $set: rollbackSnapshot(version, timestamp) }); await addEvent({ tenantId: request.appRecord.tenant_id, appId: request.appRecord.id, type: 'app.rollback', message: `已回滚发布版本到 v${target}`, actor: 'builder' }); return { ok: true, version: target }; });
  app.get('/api/apps/:id/versions', { preHandler: [auth, requireApp] }, async (request) => c('app_versions').find({ app_id: request.appRecord.id }).sort({ version: -1 }).toArray());
};
